Repository TRemigi/Roll-a-Jazz, pull requests merged in 2020-10, with the labels that each got.

#32 Feature/utils
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/models/Card.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#29 debugged queries, still need to debug card route to populate user
  server/models/Card.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#41 Feature/create page
  client/src/App.js
  client/src/components/Card/index.js
  client/src/components/CardList/index.js
  client/src/components/CardToggle/index.js
  client/src/components/Carousel/index.js
  client/src/components/Footer/index.js
  client/src/index.css
  client/src/pages/Collection.js
  client/src/pages/Create.js
  client/src/pages/Home.js
Labels: enhancement

#75 QR code scanner collapses on scanning code
  client/src/components/QrButton/index.js
  client/src/components/Search/index.js
  client/src/pages/Home.js
Labels: Priority Charlie, enhancement

#102 Feature/qr code scanner success
  .gitignore
  client/debug.log
  client/src/components/QrButton/index.js
  client/src/components/Search/index.js
  client/src/components/SearchResultsModal/index.js
Labels: enhancement

#131 added authentication to paths, users redirected to login page if not …
  client/src/App.js
Labels: bug
